export const REVIEW_LIST = [
  {
    id: 1,
    imageUrl: '/src/assets/images/product/avatar1.svg',
    name: '램바나나',
    date: '25.03.12',
    star: 5,
    likeCount: 22,
    product: '[단품] 100% 땅콩버터 스무스',
    review: '땅콩 버터의 깊은 맛이 우유와 잘 어울려요. 손님들이 무척 좋아하셔서 3번째 재구매 했습니다.',
    images: [
      '/src/assets/images/product/1-1.svg',
      '/src/assets/images/product/1-2.svg',
      '/src/assets/images/product/1-3.svg',
      '/src/assets/images/product/1-4.svg',
      '/src/assets/images/product/1-5.svg',
    ],
  },
  {
    id: 2,
    imageUrl: '/src/assets/images/product/avatar2.svg',
    name: '말차와녹차의차이',
    date: '25.03.12',
    star: 4,
    likeCount: 12,
    product: '[단품] 100% 땅콩버터 스무스',
    review:
      '피스타치오의 깊은 맛이 우유와 잘 어울려요. 손님들이 무척 좋아하셔서 3번째 재구매 했습니다. 피스타치오와 말차 맛을 헷갈리시는 분들이 많은데 사실 말이 안 된다고 생각하긴 합니다. 말차 덕후로서 말차 맛집을 추천 드리자면 홍대 롱베케이션 말차 롤케이크를 꼭 드셔야 합니다. 요즘 롯데에서 말차 빼빼로랑 말차 빈츠도 나왔다고 하던데 저는 영국에 있어서 맛도 못 봤네요. 설마 제가 한국 들어가면 단종돼 있는 건 아니겠죠...',
    images: ['/src/assets/images/product/1-6.svg', '/src/assets/images/product/1-3.svg', '/src/assets/images/product/1-1.svg'],
  },
  {
    id: 3,
    imageUrl: '/src/assets/images/product/avatar3.svg',
    name: '지금은1시18분',
    date: '25.03.12',
    star: 5,
    likeCount: 39,
    product: '[단품] 100% 땅콩버터 스무스',
    review: '다른 땅콩 버터도 다 구매해서 사용해봤는데 이게 제일 덜 부담스러운 맛이에요. 너무 달기만 하지 않아서 좋아요.',
    images: [],
  },
  {
    id: 4,
    imageUrl: '/src/assets/images/product/avatar4.svg',
    name: '버터덕후',
    date: '25.03.11',
    star: 5,
    likeCount: 17,
    product: '[단품] 100% 땅콩버터 스무스',
    review: '빵에 발라 먹으려고 샀는데 그냥 떠먹어도 너무 맛있어요. 고소하고 부드러워요!',
    images: ['/src/assets/images/product/1-7.svg', '/src/assets/images/product/1-2.svg'],
  },
  {
    id: 5,
    imageUrl: '/src/assets/images/product/avatar5.svg',
    name: '딸기샌드',
    date: '25.03.10',
    star: 3,
    likeCount: 8,
    product: '[단품] 100% 땅콩버터 스무스',
    review: '조금 텁텁한 감이 있었지만, 우유랑 같이 먹으면 괜찮았어요. 재구매는 고민 중입니다.',
    images: ['/src/assets/images/product/1-8.svg'],
  },
  {
    id: 6,
    imageUrl: '/src/assets/images/product/avatar6.svg',
    name: '일몰과 일출 색은 같을까',
    date: '25.03.12',
    star: 4,
    likeCount: 34,
    product: '[단품] 100% 땅콩버터 스무스',
    review: '땅콩 알레지 있는 줄 모르고 먹어서 죽을 뻔했어요. 근데 맛은 있어서 남은 건 다 아는 동생 줬네요.',
    images: ['/src/assets/images/product/1-4.svg', '/src/assets/images/product/1-7.svg'],
  },
  {
    id: 7,
    imageUrl: '/src/assets/images/product/avatar7.svg',
    name: '램바나나',
    date: '25.03.12',
    star: 5,
    likeCount: 12,
    product: '[기획 세트] 100% 땅콩버터 스무스 1+1',
    review: '새로 준비하고 있는 신메뉴 재료로 너무 잘 사용했습니다. 다른 회사 제품보다 훨씬 덜 달아서 디저트용으로 좋아요.',
    images: ['/src/assets/images/product/1-2.svg', '/src/assets/images/product/1-6.svg'],
  },
];
