export const CARTLIST = [
  {
    id: 1,
    company: '포레스티',
    name: '복음자리 100% 땅콩버터 스무스 280g',
    option: '[단품] 땅콩 버터 스무스',
    quantity: 1,
    originalPrice: 31000,
    price: 23430,
    imageUrl: '/src/assets/images/recommand/1.svg',
  },
  {
    id: 2,
    company: '카누',
    name: '미니 다크 아메리카노 120T + 120T',
    option: '[기획 세트] 150스틱 X 2',
    quantity: 2,
    originalPrice: 31000,
    price: 23920,
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  {
    id: 3,
    company: '카누',
    name: '미니 다크 아메리카노 120T + 120T',
    option: '[기획 세트] 150스틱 X 2',
    quantity: 2,
    originalPrice: 31000,
    price: 23920,
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  {
    id: 4,
    company: '카누',
    name: '미니 다크 아메리카노 120T + 120T',
    option: '[기획 세트] 150스틱 X 2',
    quantity: 2,
    originalPrice: 31000,
    price: 23920,
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  // 필요하면 추가...
];
