export const QUERY_KEYS = {
  GET_USER_INFO: ['getUserInfo'],
  PAYMENT_PREPARE: ['paymentPrepare'],
  PAYMENT_CONFIRM: ['paymentConfirm'],
  GET_HOME_PRODUCT: ['getHomeProduct'],
  GET_SEARCH_KEYWORD: ['getSearchKeyword'],
  GET_CATEGORY_PRODUCTS: ['CATEGORY_PRODUCTS'],
  GET_PRODUCT_DETAIL: ['getProductDetail'],
  GET_PRODUCT_OPTION: ['getProductOption'],
  GET_COUPONS: ['getCoupons'],
  GET_NOTI_LIST: ['getNotiList'],
  GET_NOTI_UNREAD: ['getNotiUnread'],
  GET_PRODUCT_REVIEW: ['getProductReview'],
  GET_RECENT_SEARCH: ['getRecentSearch'],
  GET_PHOTO: ['getPhoto'],
  GET_POINTS: ['getPoints'],
};
