export const QUERY_KEYS = {
  GET_USER_INFO: ['getUserInfo'],
  GET_TEAM_PRODUCTS: ['getTeamProducts'],
  GET_REVIEWS: ['getReviews'],
  GET_HOME_PRODUCT: ['getHomeProduct'],
  GET_SEARCH_KEYWORD: ['getSearchKeyword'],
  GET_CATEGORY_PRODUCTS: ['CATEGORY_PRODUCTS'],
  GET_PRODUCT_DETAIL: ['getProductDetail'],
  GET_COUPONS: ['getCoupons'],
  GET_NOTI_LIST: ['getNotiList'],
  GET_NOTI_UNREAD: ['getNotiUnread'],
  GET_PRODUCT_REVIEW: ['getProductReview'],
  GET_RECENT_SEARCH: ['getRecentSearch'],
  GET_PHOTO: ['getPhoto'],
  GET_POINTS: ['getPoints'],
  GET_REVIEWABLE: ['getReviewable'],
  GET_MY_REVIEW: ['getMyReview'],
  GET_ADDRESSES: ['getAddresses'],
  GET_ADDRESS: (id: number) => ['getAddress', id],
  GET_CART_ITEMS: ['cartItems'],
  GET_PRODUCT_OPTIONS: (productId: number) => ['productOptions', productId],
  GET_KEYWORD_PRODUCTS: ['GET_KEYWORD_PRODUCTS'],
};
