export const NEWLIST = [
  {
    id: 1,
    sale: 15,
    price: 23430,
    name: '바겐슈타이거 인덕션 코팅 냄비 4종 세트',
    company: '바겐슈타이거',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/new/1.svg',
  },
  {
    id: 2,
    sale: 20,
    price: 39508,
    name: '알로에베라 세탁 세제 3L 2개',
    company: '프로쉬',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/new/2.svg',
  },
  {
    id: 3,
    sale: 0,
    price: 20080,
    name: '워싱 소다 대용량 3kg 버킷',
    company: '탄산소다',
    star: 4.2,
    review: 19,
    tag: '',
    imageUrl: '/src/assets/images/new/3.svg',
  },
  {
    id: 4,
    sale: 20,
    price: 20838,
    name: '수건 오슬로 면 30수 5장 (아이보리)',
    company: '송월타올',
    star: 3.9,
    review: 24,
    tag: '',
    imageUrl: '/src/assets/images/new/4.svg',
  },
  {
    id: 5,
    sale: 43,
    price: 23430,
    name: '고단백 두유 190ml 48팩',
    company: '매일유업',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/new/5.svg',
  },
  {
    id: 6,
    sale: 12,
    price: 42838,
    name: '땅콩버터 수퍼청크 1.36kg',
    company: '스키피',
    star: 3.9,
    review: 29,
    tag: '',
    imageUrl: '/src/assets/images/new/6.svg',
  },
  {
    id: 7,
    sale: 0,
    price: 34710,
    name: '만년필 커스텀 743 FK203830 축촉',
    company: '카이더',
    star: 4.2,
    review: 19,
    tag: '',
    imageUrl: '/src/assets/images/new/7.svg',
  },
  {
    id: 8,
    sale: 15,
    price: 37290,
    name: '모든 순간 스카치 매직 테이프 8개입',
    company: '제이큐',
    star: 3.9,
    review: 383,
    tag: '',
    imageUrl: '/src/assets/images/new/8.svg',
  },
];
