export const RECOMMANDS = [
  {
    id: 1,
    sale: 15,
    price: 23430,
    name: '복음자리 100% 땅콩버터 스무스 280g',
    company: '복음자리',
    star: 4.5,
    review: 150,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/1.svg',
  },
  {
    id: 2,
    sale: 20,
    price: 42838,
    name: '미니 다크 아메리카노 120T + 120T',
    company: '카누',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  {
    id: 3,
    sale: 0,
    price: 12340,
    name: '멸균우유 흰우유 100ml X 10개',
    company: '서울우유',
    star: 4.9,
    review: 179,
    tag: '',
    imageUrl: '/src/assets/images/recommand/3.svg',
  },
  {
    id: 4,
    sale: 12,
    price: 42198,
    name: '클래식 화이트에디션 혼합 8조 세트',
    company: '글라스락',
    star: 4.5,
    review: 24,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/4.svg',
  },
  {
    id: 5,
    sale: 15,
    price: 21090,
    name: '웨어러블 천연 라텍스 고무장갑 1켤레 대형',
    company: '프로텍트랩',
    star: 3.5,
    review: 2345,
    tag: '',
    imageUrl: '/src/assets/images/recommand/5.svg',
  },
  {
    id: 6,
    sale: 40,
    price: 2838,
    name: '팔도 비빔장 시그니처 소스 380g 1개',
    company: '팔도',
    star: 3.9,
    review: 232,
    tag: '',
    imageUrl: '/src/assets/images/recommand/6.svg',
  },
  {
    id: 7,
    sale: 0,
    price: 31200,
    name: '유기농 100% 엑스트라버진 올리브오일 1L',
    company: '바쏘',
    star: 4.2,
    review: 19,
    tag: '인기',
    imageUrl: '/src/assets/images/recommand/7.svg',
  },
  {
    id: 8,
    sale: 10,
    price: 12838,
    name: '오뚜기 햇반 270g 24개',
    company: '오뚜기',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/recommand/8.svg',
  },
];
