export const TOTALLIST = [
  {
    id: 1,
    discountRate: 15,
    price: 23430,
    name: '바겐슈타이거 인덕션 코팅 냄비 4종 세트',
    store: '바겐슈타이거',
    rating: 4.5,
    reviewCount: 150,
    imageUrl: '/src/assets/images/new/1.svg',
  },
  {
    id: 2,
    discountRate: 20,
    price: 39508,
    name: '알로에베라 세탁 세제 3L 2개',
    store: '프로쉬',
    rating: 3.9,
    reviewCount: 214,
    imageUrl: '/src/assets/images/new/2.svg',
  },
  {
    id: 3,
    discountRate: 0,
    price: 20080,
    name: '워싱 소다 대용량 3kg 버킷',
    store: '탄산소다',
    rating: 4.2,
    reviewCount: 19,
    imageUrl: '/src/assets/images/new/3.svg',
  },
  {
    id: 4,
    discountRate: 20,
    price: 20838,
    name: '수건 오슬로 면 30수 5장 (아이보리)',
    store: '송월타올',
    rating: 3.9,
    reviewCount: 24,
    imageUrl: '/src/assets/images/new/4.svg',
  },
  {
    id: 5,
    discountRate: 43,
    price: 23430,
    name: '고단백 두유 190ml 48팩',
    store: '매일유업',
    rating: 4.5,
    reviewCount: 150,
    imageUrl: '/src/assets/images/new/5.svg',
  },
  {
    id: 6,
    discountRate: 12,
    price: 42838,
    name: '땅콩버터 수퍼청크 1.36kg',
    store: '스키피',
    rating: 3.9,
    reviewCount: 29,
    imageUrl: '/src/assets/images/new/6.svg',
  },
  {
    id: 7,
    discountRate: 0,
    price: 34710,
    name: '만년필 커스텀 743 FK203830 축촉',
    store: '카이더',
    rating: 4.2,
    reviewCount: 19,
    imageUrl: '/src/assets/images/new/7.svg',
  },
  {
    id: 8,
    discountRate: 15,
    price: 37290,
    name: '모든 순간 스카치 매직 테이프 8개입',
    store: '제이큐',
    rating: 3.9,
    reviewCount: 383,
    imageUrl: '/src/assets/images/new/8.svg',
  },
  {
    id: 9,
    discountRate: 25,
    price: 23430,
    name: '레오나르디 화이트 발사믹식 콘디멘토 비앙코 250ml X 2개',
    store: '레오나르디',
    rating: 4.5,
    reviewCount: 150,
    imageUrl: '/src/assets/images/popular/1.svg',
  },
  {
    id: 10,
    discountRate: 30,
    price: 42838,
    name: '덴마크 유산균 이야기 170mg X 60캡슐 X 6박스',
    store: '노르딕',
    rating: 3.9,
    reviewCount: 214,
    imageUrl: '/src/assets/images/popular/2.svg',
  },
  {
    id: 11,
    discountRate: 0,
    price: 23230,
    name: '베네팜 유기농 곱슬케일 4박스 동결건조',
    store: '베네팜',
    rating: 4.2,
    reviewCount: 183,
    tag: '신규',
    imageUrl: '/src/assets/images/popular/3.svg',
  },
  {
    id: 12,
    discountRate: 20,
    price: 19838,
    name: '코스트코 순수 아보카도 PURE 100% 1L',
    store: '코스트코',
    rating: 3.9,
    reviewCount: 123,
    imageUrl: '/src/assets/images/popular/4.svg',
  },
  {
    id: 13,
    discountRate: 15,
    price: 23430,
    name: '프렉션드 스탠 냄비 양수 20cm',
    store: '퀸센스',
    rating: 4.5,
    reviewCount: 150,
    imageUrl: '/src/assets/images/popular/5.svg',
  },
  {
    id: 14,
    discountRate: 20,
    price: 42838,
    name: '비욘봉투 세로형 편지봉투 용돈 상품권 선물',
    store: '핫트랙스',
    rating: 3.9,
    reviewCount: 214,
    imageUrl: '/src/assets/images/popular/6.svg',
  },
  {
    id: 15,
    discountRate: 0,
    price: 3430,
    name: '서울우유',
    store: '바스틀리',
    rating: 4.2,
    reviewCount: 19,
    imageUrl: '/src/assets/images/popular/7.svg',
  },
  {
    id: 16,
    discountRate: 20,
    price: 32828,
    name: '키스해링 대나무 펄프 뽑아쓰는 키친 타올 휴대용 100매',
    store: '좋은 느낌',
    rating: 3.9,
    reviewCount: 214,
    tag: '신규',
    imageUrl: '/src/assets/images/popular/8.svg',
  },
  {
    id: 17,
    discountRate: 15,
    price: 23430,
    name: '복음자리 100% 땅콩버터 스무스 280g',
    store: '복음자리',
    rating: 4.5,
    reviewCount: 150,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/1.svg',
  },
  {
    id: 18,
    discountRate: 20,
    price: 42838,
    name: '미니 다크 아메리카노 120T + 120T',
    store: '카누',
    rating: 3.9,
    reviewCount: 214,
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  {
    id: 19,
    discountRate: 0,
    price: 12340,
    name: '멸균우유 흰우유 100ml X 10개',
    store: '서울우유',
    rating: 4.9,
    reviewCount: 179,
    imageUrl: '/src/assets/images/recommand/3.svg',
  },
  {
    id: 20,
    discountRate: 12,
    price: 42198,
    name: '클래식 화이트에디션 혼합 8조 세트',
    store: '글라스락',
    rating: 4.5,
    reviewCount: 24,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/4.svg',
  },
  {
    id: 21,
    discountRate: 15,
    price: 21090,
    name: '웨어러블 천연 라텍스 고무장갑 1켤레 대형',
    store: '프로텍트랩',
    rating: 3.5,
    reviewCount: 2345,
    imageUrl: '/src/assets/images/recommand/5.svg',
  },
  {
    id: 22,
    discountRate: 40,
    price: 2838,
    name: '팔도 비빔장 시그니처 소스 380g 1개',
    store: '팔도',
    rating: 3.9,
    reviewCount: 232,
    imageUrl: '/src/assets/images/recommand/6.svg',
  },
  {
    id: 23,
    discountRate: 0,
    price: 31200,
    name: '유기농 100% 엑스트라버진 올리브오일 1L',
    store: '바쏘',
    rating: 4.2,
    reviewCount: 19,
    tag: '인기',
    imageUrl: '/src/assets/images/recommand/7.svg',
  },
  {
    id: 24,
    discountRate: 10,
    price: 12838,
    name: '오뚜기 햇반 270g 24개',
    store: '오뚜기',
    rating: 3.9,
    reviewCount: 214,
    imageUrl: '/src/assets/images/recommand/8.svg',
  },
];
