export const TOTALLIST = [
  {
    id: 1,
    sale: 15,
    price: 23430,
    name: '바겐슈타이거 인덕션 코팅 냄비 4종 세트',
    company: '바겐슈타이거',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/new/1.svg',
  },
  {
    id: 2,
    sale: 20,
    price: 39508,
    name: '알로에베라 세탁 세제 3L 2개',
    company: '프로쉬',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/new/2.svg',
  },
  {
    id: 3,
    sale: 0,
    price: 20080,
    name: '워싱 소다 대용량 3kg 버킷',
    company: '탄산소다',
    star: 4.2,
    review: 19,
    tag: '',
    imageUrl: '/src/assets/images/new/3.svg',
  },
  {
    id: 4,
    sale: 20,
    price: 20838,
    name: '수건 오슬로 면 30수 5장 (아이보리)',
    company: '송월타올',
    star: 3.9,
    review: 24,
    tag: '',
    imageUrl: '/src/assets/images/new/4.svg',
  },
  {
    id: 5,
    sale: 43,
    price: 23430,
    name: '고단백 두유 190ml 48팩',
    company: '매일유업',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/new/5.svg',
  },
  {
    id: 6,
    sale: 12,
    price: 42838,
    name: '땅콩버터 수퍼청크 1.36kg',
    company: '스키피',
    star: 3.9,
    review: 29,
    tag: '',
    imageUrl: '/src/assets/images/new/6.svg',
  },
  {
    id: 7,
    sale: 0,
    price: 34710,
    name: '만년필 커스텀 743 FK203830 축촉',
    company: '카이더',
    star: 4.2,
    review: 19,
    tag: '',
    imageUrl: '/src/assets/images/new/7.svg',
  },
  {
    id: 8,
    sale: 15,
    price: 37290,
    name: '모든 순간 스카치 매직 테이프 8개입',
    company: '제이큐',
    star: 3.9,
    review: 383,
    tag: '',
    imageUrl: '/src/assets/images/new/8.svg',
  },
  {
    id: 9,
    sale: 25,
    price: 23430,
    name: '레오나르디 화이트 발사믹식 콘디멘토 비앙코 250ml X 2개',
    company: '레오나르디',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/popular/1.svg',
  },
  {
    id: 10,
    sale: 30,
    price: 42838,
    name: '덴마크 유산균 이야기 170mg X 60캡슐 X 6박스',
    company: '노르딕',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/popular/2.svg',
  },
  {
    id: 11,
    sale: 0,
    price: 23230,
    name: '베네팜 유기농 곱슬케일 4박스 동결건조',
    company: '베네팜',
    star: 4.2,
    review: 183,
    tag: '신규',
    imageUrl: '/src/assets/images/popular/3.svg',
  },
  {
    id: 12,
    sale: 20,
    price: 19838,
    name: '코스트코 순수 아보카도 PURE 100% 1L',
    company: '코스트코',
    star: 3.9,
    review: 123,
    tag: '',
    imageUrl: '/src/assets/images/popular/4.svg',
  },
  {
    id: 13,
    sale: 15,
    price: 23430,
    name: '프렉션드 스탠 냄비 양수 20cm',
    company: '퀸센스',
    star: 4.5,
    review: 150,
    tag: '',
    imageUrl: '/src/assets/images/popular/5.svg',
  },
  {
    id: 14,
    sale: 20,
    price: 42838,
    name: '비욘봉투 세로형 편지봉투 용돈 상품권 선물',
    company: '핫트랙스',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/popular/6.svg',
  },
  {
    id: 15,
    sale: 0,
    price: 3430,
    name: '서울우유',
    company: '바스틀리',
    star: 4.2,
    review: 19,
    tag: '',
    imageUrl: '/src/assets/images/popular/7.svg',
  },
  {
    id: 16,
    sale: 20,
    price: 32828,
    name: '키스해링 대나무 펄프 뽑아쓰는 키친 타올 휴대용 100매',
    company: '좋은 느낌',
    star: 3.9,
    review: 214,
    tag: '신규',
    imageUrl: '/src/assets/images/popular/8.svg',
  },
  {
    id: 17,
    sale: 15,
    price: 23430,
    name: '복음자리 100% 땅콩버터 스무스 280g',
    company: '복음자리',
    star: 4.5,
    review: 150,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/1.svg',
  },
  {
    id: 18,
    sale: 20,
    price: 42838,
    name: '미니 다크 아메리카노 120T + 120T',
    company: '카누',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/recommand/2.svg',
  },
  {
    id: 19,
    sale: 0,
    price: 12340,
    name: '멸균우유 흰우유 100ml X 10개',
    company: '서울우유',
    star: 4.9,
    review: 179,
    tag: '',
    imageUrl: '/src/assets/images/recommand/3.svg',
  },
  {
    id: 20,
    sale: 12,
    price: 42198,
    name: '클래식 화이트에디션 혼합 8조 세트',
    company: '글라스락',
    star: 4.5,
    review: 24,
    tag: 'new',
    imageUrl: '/src/assets/images/recommand/4.svg',
  },
  {
    id: 21,
    sale: 15,
    price: 21090,
    name: '웨어러블 천연 라텍스 고무장갑 1켤레 대형',
    company: '프로텍트랩',
    star: 3.5,
    review: 2345,
    tag: '',
    imageUrl: '/src/assets/images/recommand/5.svg',
  },
  {
    id: 22,
    sale: 40,
    price: 2838,
    name: '팔도 비빔장 시그니처 소스 380g 1개',
    company: '팔도',
    star: 3.9,
    review: 232,
    tag: '',
    imageUrl: '/src/assets/images/recommand/6.svg',
  },
  {
    id: 23,
    sale: 0,
    price: 31200,
    name: '유기농 100% 엑스트라버진 올리브오일 1L',
    company: '바쏘',
    star: 4.2,
    review: 19,
    tag: '인기',
    imageUrl: '/src/assets/images/recommand/7.svg',
  },
  {
    id: 24,
    sale: 10,
    price: 12838,
    name: '오뚜기 햇반 270g 24개',
    company: '오뚜기',
    star: 3.9,
    review: 214,
    tag: '',
    imageUrl: '/src/assets/images/recommand/8.svg',
  },
];
